first-iter
maliven1/rest-api pull request #1
Opened 2024-07-24 18:27 UTC by maliven1

2024-07-24 22:47 UTC, dirtymew requested changes
Привет Денис

хорошая работа - API описан верно

есть что поправить см PR

2024-07-24 22:47 UTC, dirtymew commented on precode.go
> +func postTasks(w http.ResponseWriter, r *http.Request) {
лучше назвать addTask или createTask

2024-07-24 22:47 UTC, dirtymew commented on precode.go
> +	_, err := buf.ReadFrom(r.Body)
на будущее тут эффективнее json.Decoder использовать

2024-07-24 22:47 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
тут вот стоит поправить

Код не только добавляет но и обновляет задачу - стоит сделать проверку и вернуть ошибку

2024-07-24 22:47 UTC, dirtymew commented on precode.go
> +	} else {
тут не ошибка но лучше не использовать else если есть такая возможность

можно так 

```
	if _, ok := tasks[id]; !ok {
		http.Error(w, "Задача не найдена", http.StatusBadRequest)
		return
	}

        delete(tasks, id)
```

2024-07-24 22:47 UTC, dirtymew commented on precode.go
> +	w.Write(resp)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

2024-07-25 12:49 UTC, dirtymew approved these changes
Денис

зачет - есть помарка не критичная обрати внимание )

2024-07-25 12:49 UTC, dirtymew commented on precode.go
> +	w.Write(resp)
в одно месте поправил в другом нет

на ревью комментарии часто относятся ко всему не только к конкретной строчке

2024-07-25 13:04 UTC, maliven1 commented on precode.go
> +	w.Write(resp)
Принято, спасибо

2024-08-23 16:07 UTC, merged